//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditComponent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditComponent()
        {
            this.AuditComponentDetails = new HashSet<AuditComponentDetail>();
        }
    
        public decimal ID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> SubDeptID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<System.TimeSpan> AuditTime { get; set; }
        public string AuditerName { get; set; }
        public string InstitutionAddress { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string InstitutionHead { get; set; }
        public string HeadPhoneNo { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual SubDepartment SubDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditComponentDetail> AuditComponentDetails { get; set; }
    }
}
