//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditComponentDetail
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ComponentID { get; set; }
        public Nullable<decimal> StaffTypeId { get; set; }
        public Nullable<decimal> StaffTypeSubId { get; set; }
        public string FullTime { get; set; }
        public string PartTime { get; set; }
        public string Visting { get; set; }
        public string Male { get; set; }
        public string Female { get; set; }
    
        public virtual AuditComponent AuditComponent { get; set; }
        public virtual StaffType StaffType { get; set; }
        public virtual StaffSubType StaffSubType { get; set; }
    }
}
