//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int audit_id { get; set; }
        public Nullable<decimal> audit_year { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> starting_date { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public string description { get; set; }
    }
}
