//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplianceRatedNumber
    {
        public int ID { get; set; }
        public Nullable<int> AuditID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> RatedValue { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> OnCreated { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ImagePath { get; set; }
        public string remarks { get; set; }
    }
}
