//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string Prefix { get; set; }
        public string EFName { get; set; }
        public string ELName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> PayScale { get; set; }
        public string HPhoneNo { get; set; }
        public string OphoneNo { get; set; }
        public string OfficeAdd { get; set; }
        public string HomeAdd { get; set; }
        public string Gender { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> SubDeptID { get; set; }
        public Nullable<int> Profession_Code { get; set; }
        public string Mobile_No { get; set; }
        public string PMDC_No { get; set; }
        public Nullable<System.DateTime> Date_of_Termination { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ConfirmPass { get; set; }
        public string Image { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
