//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Area
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Area()
    {
        this.SaleOfficers = new HashSet<SaleOfficer>();
    }

    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public int RegionID { get; set; }
    public int CityID { get; set; }
    public string ShortCode { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }

    public virtual City City { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SaleOfficer> SaleOfficers { get; set; }
}

public partial class City
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public City()
    {
        this.Areas = new HashSet<Area>();
        this.Dealers = new HashSet<Dealer>();
        this.SaleOfficers = new HashSet<SaleOfficer>();
    }

    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public int RegionID { get; set; }
    public string ShortCode { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool IsActive { get; set; }
    public bool IsDeleted { get; set; }
    public int CreatedBy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Area> Areas { get; set; }
    public virtual Region Region { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Dealer> Dealers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SaleOfficer> SaleOfficers { get; set; }
}

public partial class Dealer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Dealer()
    {
        this.Retailers = new HashSet<Retailer>();
    }

    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> SaleOfficerID { get; set; }
    public Nullable<int> CityID { get; set; }
    public string Address { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }

    public virtual City City { get; set; }
    public virtual SaleOfficer SaleOfficer { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Retailer> Retailers { get; set; }
}

public partial class Job
{
    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> FOS { get; set; }
    public Nullable<int> AreaID { get; set; }
    public Nullable<System.DateTime> DateFrom { get; set; }
    public Nullable<System.DateTime> DateTo { get; set; }
    public Nullable<int> Criteria { get; set; }
    public Nullable<int> Customer { get; set; }
    public Nullable<System.DateTime> LastUpdate { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }
}

public partial class LoginHistory
{
    public int TID { get; set; }
    public int ID { get; set; }
    public int UserID { get; set; }
    public string Password { get; set; }
    public System.DateTime LoginFrom { get; set; }
    public System.DateTime LoginTo { get; set; }
    public System.DateTime CreatedDate { get; set; }
}

public partial class Page
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Page()
    {
        this.Pages1 = new HashSet<Page>();
        this.RolePages = new HashSet<RolePage>();
    }

    public int PageID { get; set; }
    public Nullable<int> ParentPageID { get; set; }
    public string Path { get; set; }
    public string Type { get; set; }
    public string Name { get; set; }
    public string MenuInitials { get; set; }
    public string Controller { get; set; }
    public string Action { get; set; }
    public Nullable<bool> ShowMenu { get; set; }
    public Nullable<int> RoleType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Page> Pages1 { get; set; }
    public virtual Page Page1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RolePage> RolePages { get; set; }
}

public partial class Region
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Region()
    {
        this.Cities = new HashSet<City>();
        this.RegionalHeadRegions = new HashSet<RegionalHeadRegion>();
    }

    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public string ShortCode { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsActive { get; set; }
    public System.DateTime LastUpdate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<City> Cities { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RegionalHeadRegion> RegionalHeadRegions { get; set; }
}

public partial class RegionalHead
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RegionalHead()
    {
        this.RegionalHeadRegions = new HashSet<RegionalHeadRegion>();
        this.SaleOfficers = new HashSet<SaleOfficer>();
    }

    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool IsActive { get; set; }
    public bool IsDeleted { get; set; }
    public int CreatedBy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RegionalHeadRegion> RegionalHeadRegions { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SaleOfficer> SaleOfficers { get; set; }
}

public partial class RegionalHeadRegion
{
    public int ID { get; set; }
    public int RegionHeadID { get; set; }
    public int RegionID { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool IsActive { get; set; }
    public bool IsDeleted { get; set; }
    public int CreatedBy { get; set; }

    public virtual RegionalHead RegionalHead { get; set; }
    public virtual Region Region { get; set; }
}

public partial class Retailer
{
    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> DealerID { get; set; }
    public int SaleOfficerID { get; set; }
    public string ShopName { get; set; }
    public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    public string LocationMargin { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public Nullable<int> CityID { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string Address { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool Status { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }

    public virtual Dealer Dealer { get; set; }
    public virtual SaleOfficer SaleOfficer { get; set; }
}

public partial class Role
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {
        this.RolePages = new HashSet<RolePage>();
        this.Users = new HashSet<User>();
    }

    public int RoleID { get; set; }
    public string RoleName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RolePage> RolePages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class RolePage
{
    public int RoleID { get; set; }
    public int PageID { get; set; }
    public Nullable<int> Access { get; set; }
    public Nullable<System.DateTime> LastUpdate { get; set; }
    public Nullable<bool> Read { get; set; }
    public Nullable<bool> Write { get; set; }
    public Nullable<bool> Update { get; set; }
    public Nullable<bool> Delete { get; set; }
    public Nullable<bool> Status { get; set; }

    public virtual Page Page { get; set; }
    public virtual Role Role { get; set; }
}

public partial class SaleOfficer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SaleOfficer()
    {
        this.Dealers = new HashSet<Dealer>();
        this.Retailers = new HashSet<Retailer>();
        this.Areas = new HashSet<Area>();
    }

    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> RegionalHeadID { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public Nullable<int> CityID { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }
    public bool IsDeleted { get; set; }
    public string Password { get; set; }

    public virtual City City { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Dealer> Dealers { get; set; }
    public virtual RegionalHead RegionalHead { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Retailer> Retailers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Area> Areas { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Roles = new HashSet<Role>();
    }

    public int ID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public Nullable<int> RoleID { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
    public bool IsDeleted { get; set; }
    public bool IsActive { get; set; }
    public int CreatedBy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Role> Roles { get; set; }
}

public partial class GetDealersBySo_Result
{
    public int TID { get; set; }
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> SaleOfficerID { get; set; }
    public Nullable<int> CityID { get; set; }
    public string Address { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public System.DateTime CreatedDate { get; set; }
    public System.DateTime LastUpdate { get; set; }
}
