//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int TID { get; set; }
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Password { get; set; }
        public System.DateTime LoginFrom { get; set; }
        public System.DateTime LoginTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
