//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.Pages1 = new HashSet<Page>();
            this.RolePages = new HashSet<RolePage>();
        }
    
        public int PageID { get; set; }
        public Nullable<int> ParentPageID { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string MenuInitials { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<bool> ShowMenu { get; set; }
        public Nullable<int> RoleType { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page> Pages1 { get; set; }
        public virtual Page Page1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolePage> RolePages { get; set; }
    }
}
